Classes/Django-Basic/blog/urls.py
from blog import views
from django.urls import path

app_name = 'blog'

# blog/
# Django URLs: https://docs.djangoproject.com/en/5.2/topics/http/urls/
urlpatterns = [
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo'),
    path('', views.blog, name='home'),
]

Classes/Django-Basic/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

Classes/Django-Basic/project/urls.py
# HTTP Request <-> HTTP Response
# MVT (MVC)

"""
URL configuration for project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

Classes/Django-Basic/blog/views.py
from typing import Any

from blog.data import posts

from django.shortcuts import render
from django.http import Http404, HttpRequest

def blog(request):
    print('blog')

    context = {
        # 'text': 'Olá blog',
        'posts': posts
    }

    return render(
        request,
        'blog/index.html',
        context
    )


def exemplo(request):
    print('exemplo')

    context = {
        'text': 'Olá exemplo',
        'title': 'Essa é uma página de exemplo - ',
    }

    return render(
        request,
        'blog/exemplo.html',
        context
    )
    
    
def post(request: HttpRequest, post_id: int):
    found_post: dict[str, Any] | None = None
    
    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
        
    if found_post is None:
        raise Http404('Post não existe.')

    context = {
        # 'text': 'Olá blog',
        'post': found_post,
        'title': found_post['title'] + ' - ',
    }

    return render(
        request,
        'blog/post.html',
        context
    )

Classes/Django-Basic/home/views.py
from django.shortcuts import render


def home(request):
    print('home')

    context = {
        'text': 'Olá home'
    }

    return render(
        request,
        'home/index.html',
        context,
    )

Classes/Django-Basic/blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

Classes/Django-Basic/blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
  {% for post in posts %}
    {% include 'global/partials/postblock.html' %}
  {% endfor %}
{% endblock posts %}

Classes/Django-Basic/blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
    <article class="post single-post">
    <header>
      <h1 class="post__title">
        <a href="{% url "blog:post" post.id %}">
          {{ post.title }}
        </a>
      </h1>
    </header>
    <div class="post__body">{{ post.body }}</div>
  </article>
{% endblock posts %}

Classes/Django-Basic/home/templates/home/index.html
{% extends 'global/base.html' %}

{% block texto %} 
  {{ text }}
{% endblock texto %}

{% block home %} 
  <h1>HOME</h1>
{% endblock home %}